### ISSUE TITLE
NE TÉLÉCHARGEZ PAS

### ISSUE THREAD

**Issue by douxxu** [Kisakay/image_ip_grabber#1]
# il y a un tojan !

Metasploit a détecté un tojan de type lavabo dans le fichier IMG/pov.png !!!
Faites très attention à ces fausses promesses qui ne sont que des virus !!!!!

(Si vous voulez un jeu steam gratuit, allez sur https://steam.douxx.xyz/grab/games/81625181.php

**Comment by Kisakay** [comment]
Merde ! Tu as casser mon Business…

😂

**Comment by Kisakay** [comment]
😂
